# Use postgres/example user/password credentials
volumes:
  db_data: {}
  ollama_data: {}

networks:
  budget2025-rag-network:
    driver: bridge

services:
  db:
    image: pgvector/pgvector:pg17 # postgres with pgvector extension
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}

    ports:
      - ${DB_PORT}:5432
    networks:
      - budget2025-rag-network

  ollama:
    # Uncomment below for GPU support
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu

    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - budget2025-rag-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HUGGING_FACE_TOKEN: ${HUGGING_FACE_TOKEN}
        SENTENCE_TRANSFORMER_RERANKER_MODEL: ${SENTENCE_TRANSFORMER_RERANKER_MODEL}
        HUGGING_FACE_EMBEDDING_MODEL: ${HUGGING_FACE_EMBEDDING_MODEL}
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      HUGGING_FACE_TOKEN: ${HUGGING_FACE_TOKEN}
      HUGGING_FACE_EMBEDDING_MODEL: ${HUGGING_FACE_EMBEDDING_MODEL}
      SIMILARITY_TOP_K: ${SIMILARITY_TOP_K}
      SIMILARITY_CUTOFF: ${SIMILARITY_CUTOFF}
      JINA_RERANKER_MODEL: ${JINA_RERANKER_MODEL}
      JINA_RERANKER_TOP_N: ${JINA_RERANKER_TOP_N}
      JINA_API_KEY: ${JINA_API_KEY}
      SENTENCE_TRANSFORMER_RERANKER_MODEL: ${SENTENCE_TRANSFORMER_RERANKER_MODEL}
      SENTENCE_TRANSFORMER_RERANKER_TOP_N: ${SENTENCE_TRANSFORMER_RERANKER_TOP_N}
      LITELLM_LLM_RERANKER_MODEL: ${LITELLM_LLM_RERANKER_MODEL}
      LLM_RERANKER_TOP_N: ${LLM_RERANKER_TOP_N}
      LLM_RERANKER_CHOICE_BATCH_SIZE: ${LLM_RERANKER_CHOICE_BATCH_SIZE}
      LITELLM_RESPONSE_SYNTHESIZER_MODEL: ${LITELLM_RESPONSE_SYNTHESIZER_MODEL}
      LITELLM_CHAT_ENGINE_LLM_MODEL_NAME: ${LITELLM_CHAT_ENGINE_LLM_MODEL_NAME}
      MISTRAL_API_KEY: ${MISTRAL_API_KEY}
      OLLAMA_API_BASE: ${OLLAMA_API_BASE}
      TAVILY_API_KEY: ${TAVILY_API_KEY}

    ports:
      - 8501:8501 # for Streamlit app
      - 6006:6006 # for Arize Phoenix
    depends_on:
      - db
      - ollama
    networks:
      - budget2025-rag-network
